on: push
name: Main Workflow
jobs:
  tests:
    strategy:
      matrix:
        node: ['16', '14', '12']
    name: Run NPM Stuff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: npm test
